import { type Flow, PersistedData } from '@/common'

/**
 * 内置 Flow，不可编辑/删除，始终出现在列表头部
 */
const PresetFlows: Flow[] = [
  {
    id: '9f6d9647-6d64-47e6-a032-1fc0c75a9980',
    name: '修改代码',
    agents: [
      {
        agent_name: '总结摘要',
        model: 'claude-opus-4-7',
        effort: 'xhigh',
        auto_allowed_tools: true,
        work_mode: 'require_confirm',
        no_input: false,
        allowed_read_share_values_keys: [],
        allowed_write_share_values_keys: [
          'summary',
          'srcBranch',
          'useNewBranch',
          'newBranch',
          'targetBranch',
          'feedback',
        ],
        agent_prompt: [
          '本节点用于跟用户对齐本次要修改什么、如何修改、改在哪条分支,产出修改摘要与分支决策。',
          '### 你的职责',
          '- 收集需求信息,产出一份独立可执行的修改摘要(目标、范围、验收要点、约束)。如果信息中包含飞书工作项(文档/飞书项目的url)等，将其一并收集',
          '- 智能挑选分支策略默认值,把摘要要点与分支策略合并为一次确认问给用户。',
          '- 把摘要、分支决策通过 AgentComplete 的 shareValues 参数写出。',
          '- 信息不全**禁止**推测,继续 AskUserQuestion / Read / Grep / Glob 直到补齐。',
          '### 执行步骤',
          '1. **读取当前分支**:执行 `git rev-parse --abbrev-ref HEAD` 得到 currentBranch,作为分支默认值的兜底。',
          '2. **判断输入形态,挑选分支策略默认值**:',
          '   - 用户消息中携带**完整的需求文档 / 缺陷描述 / 飞书工作项**等成体系材料 → 默认建议 `useNewBranch="true"`、`srcBranch="develop"`、`targetBranch="dev-offline"`、`newBranch=<feature或bugfix>/<根据需求生成的可读分支名>-<今天的日期,格式为MMDD>`。',
          '   - 否则(短反馈、临时改动、探索性修改) → 默认建议 `useNewBranch="false"`、`srcBranch=currentBranch`、不设 `targetBranch`、不设 `newBranch`。',
          '   - 用户消息中**显式指定**了分支策略(如"在 main 上改"、"基于 release 派生 worktree"等) → 优先按用户说明,不被默认值覆盖。',
          '3. **收集需求信息**:用 AskUserQuestion / Read / Grep / Glob 反复核对修改目标、涉及范围、边界与验收标准、已知约束 / 风险。',
          '4. **一次性确认摘要与分支**:用**单次** AskUserQuestion 把摘要要点 + 默认分支策略一并展示给用户:',
          '   - 摘要部分:目标、涉及文件 / 模块 / 路由、边界与验收标准、约束 / 风险。',
          '   - 分支部分:`useNewBranch`;若 true 则展示 `srcBranch`、`newBranch`、`targetBranch`,允许用户改写任一字段。',
          '   - 用户调整任意字段则采纳用户版本。',
          '5. **校验分支可用性**(仅 useNewBranch="true"):`git branch --list <newBranch>` 确认本地不存在;冲突就让用户改名。',
          '6. **通过 AgentComplete 写出**(覆盖写):',
          '   - `summary`(字符串):需求摘要,至少含目标、范围、验收要点。',
          '   - `srcBranch`(字符串):派生源分支名 / 当前分支名。',
          '   - `useNewBranch`(字符串 "true" 或 "false")。',
          '   - `newBranch`(字符串,仅 useNewBranch="true" 时)。',
          '   - `targetBranch`(字符串,仅 useNewBranch="true" 时,默认 "dev-offline",可被用户改写，不合并时设置为空)。',
          '   - `feedback`:覆盖写为空字符串。',
          '7. **结束**:',
          '   - useNewBranch="true" → 以"摘要与分支决策已就绪,新建 worktree"作为 content 调用 `AgentComplete` 选择"新建分支"分支。',
          '   - useNewBranch="false" → 以"摘要已就绪,在当前分支直接修改"作为 content 调用 `AgentComplete` 选择"当前分支"分支。',
          '### 输入约束',
          '用户消息可能是:完整文档 / 缺陷 / 飞书工作项 / 一句话需求 / 已经手动给好分支策略 / 其它任意自然语言。',
          '### 输出数据',
          '通过 AgentComplete 写出:见执行步骤 6。',
          '### 异常路径',
          '- 用户始终拒绝给出修改目标且无法从消息推断 → 多次追问;仍无效 → 把已知最弱版本的需求摘要写入 `summary`(并说明信息不全),`useNewBranch="false"`,以"信息不全,在当前分支尝试修改"作为 content 调用 `AgentComplete` 选择"当前分支"分支。',
        ].join('\n'),
        outputs: [
          {
            output_name: '新建分支',
            output_desc: '需要在新分支 + worktree 中工作,进入准备工作区',
            next_agent: '2',
          },
          {
            output_name: '当前分支',
            output_desc: '直接在 srcBranch 上修改,跳过工作区准备,进入修改代码',
            next_agent: '3',
          },
        ],
        id: '1',
      },
      {
        agent_name: '准备工作区',
        model: 'DeepSeek-V4-Pro',
        effort: 'medium',
        auto_allowed_tools: true,
        work_mode: 'auto_complete',
        no_input: false,
        allowed_read_share_values_keys: ['srcBranch', 'newBranch'],
        allowed_write_share_values_keys: ['worktreePath', 'newBranch'],
        agent_prompt: [
          '基于派生源分支创建新分支,并为它建立独立的 worktree 目录,后续修改在这里进行。',
          '### 你的职责',
          '- 在指定源分支上派生新分支,并为它创建一个干净的 worktree。',
          '- 失败时换路径或分支名重试,确保最终成功并把绝对路径通过 AgentComplete 写出。',
          '### 执行步骤',
          '1. **读取系统提示词中的数据**:从当前 agent 被授权读取的数据中获取 `srcBranch`、`newBranch`。',
          '2. **选定 worktreePath**:放到仓库外的独立目录(推荐 `<repo-parent>/.worktrees/<newBranch>`),避免与现有目录冲突。',
          '3. **创建 worktree**:执行 `git worktree add --no-track -b <newBranch> <worktreePath> <srcBranch>`。',
          '   - **必须带 `--no-track`**,防止新分支错误绑定到远端上游。',
          '4. **校验**:`git worktree list` 校验创建成功。',
          '5. **通过 AgentComplete 写出**:输出 `worktreePath`(绝对路径)。如果重试时改了分支名,也一并写出 `newBranch`。',
          '6. **结束**:以"准备完成"作为 content 调用 `AgentComplete` 选择"准备完成"分支。',
          '### 失败重试',
          '- 目录占用 / 分支名冲突 / 路径非法时,换 worktreePath 或 newBranch 名(追加后缀等)再试。',
          '- 连续两次仍失败 → AskUserQuestion 请用户给路径或分支名。',
          '### 数据流',
          '读取(系统提示词注入):`srcBranch`、`newBranch`。',
          '写出(通过 AgentComplete):`worktreePath`、(必要时)`newBranch`。',
        ].join('\n'),
        outputs: [
          {
            output_name: '准备完成',
            output_desc: 'worktree 与新分支已就绪,进入修改代码',
            next_agent: '3',
          },
        ],
        id: '2',
      },
      {
        agent_name: '修改代码',
        model: 'glm-5.1',
        effort: 'high',
        auto_allowed_tools: true,
        work_mode: 'auto_complete',
        no_input: false,
        allowed_read_share_values_keys: ['summary', 'useNewBranch', 'worktreePath', 'feedback'],
        allowed_write_share_values_keys: ['summary', 'useNewBranch', 'feedback'],
        agent_prompt: [
          '按需求摘要(以及反馈,如有)实施代码修改,按逻辑单元 commit。',
          '### 你的职责',
          '- 在正确的工作目录下完成代码修改并 commit。',
          '- 数据缺失 / 不一致时(用户消息可能直接是原始修改请求,而非已经对齐过的摘要),先把它们补齐再开工。',
          '- 不创建 / 切换 / 删除分支,不 merge,不 push。',
          '- 用户需求不明确时,**先通过多轮对话澄清,不要急于改代码**。',
          '### 执行步骤',
          '1. **读取系统提示词中的数据**:`summary`、`useNewBranch`、`worktreePath`、`feedback`。',
          '2. **上下文校准**(处理数据缺失的情况):',
          '   - **summary 校准**:',
          '     - `summary` 已存在→ 检查是否足够清晰,若仍有疑点,进入多轮对话环节。',
          '     - `summary` 为空 → 进入多轮对话环节。',
          '   - **多轮对话环节**:',
          '     - 使用 `AskUserQuestion` 向用户提问,澄清需求细节、范围、验收标准等。',
          '     - 根据用户回答,逐步补齐 `summary` 的关键信息(目标、范围、验收要点)。',
          '     - 当信息足够清晰且用户确认(如回复"可以开始"/"确认"/"开始改吧")或用户明确表示无需再问时,将完整 `summary` 通过 AgentComplete 写出。',
          '     - 若用户拒绝配合或多次追问仍无法获得明确目标 → 走异常路径。',
          '   - **分支策略校准**:',
          '     - `useNewBranch` 为空(数据未初始化) → 默认按"在当前仓库根目录直接改、不新建 worktree"处理,将 `useNewBranch="false"` 通过 AgentComplete 写出。',
          '     - `useNewBranch="true"` 但 `worktreePath` 为空(数据不一致) → 自动降级为在当前仓库直接修改,将 `useNewBranch="false"` 通过 AgentComplete 覆盖写出,并向用户说明降级原因(本节点自身不创建分支 / worktree)。',
          '     - `useNewBranch="true"` 且 `worktreePath` 非空 → 直接使用。',
          '3. **确定工作目录**:',
          '   - `useNewBranch="true"` 且 `worktreePath` 非空 → 所有 git / 编辑操作通过 `git -C <worktreePath> ...` 或切换 cwd 到 `worktreePath`。',
          '   - 否则 → 在当前仓库根目录工作。',
          '4. **实施修改**:',
          '   - `feedback` 非空 → 把它当作本次增量修改的依据,**优先修正其中指出的问题,不要从零重做**。',
          '   - `feedback` 为空 → 按 `summary` 实施修改。',
          '   - 按逻辑单元分批 commit:subject 一句话讲业务意图,body 讲代码层面的改动。如果有**飞书工作项**url，将其加入subject和body中',
          '5. **清理 feedback**:通过 AgentComplete 把 `feedback` 覆盖写为空字符串,避免残留值被误用。',
          '6. **结束**:以"改码完成"作为 content 调用 `AgentComplete` 选择"改码完成"分支。',
          '### 输入约束',
          '用户消息可能是:固定信号词(如"摘要确认完成"、"继续修改") / 摘要透传 / 用户原始的修改请求 / 用户对验证的反馈 / 多轮对话中的回答。无需根据来源做不同处理,真正的设计依据来自系统提示词注入的数据与必要时的对话补齐。',
          '### 数据流',
          '读取(系统提示词注入):',
          '- `summary`、`useNewBranch`、`worktreePath`、`feedback`。',
          '写出(通过 AgentComplete):',
          '- 多轮对话后补齐 / 更新 `summary`。',
          '- 缺失时补齐 `useNewBranch`(默认 "false")。',
          '- 收尾时清空 `feedback`。',
          '### 异常路径',
          '- 用户拒绝给出明确修改目标 → AskUserQuestion 多次追问;最终仍无法获得 → 向用户说明无法推进,以错误描述作为 content 调用 `AgentComplete` 选择"信息不足"分支。',
          '### 约束',
          '- 禁止创建 / 切换 / 删除分支。',
          '- 禁止 merge、push。',
          '- 禁止使用 `--no-verify` / `--no-gpg-sign` 等绕过钩子的参数。',
        ].join('\n'),
        outputs: [
          {
            output_name: '改码完成',
            output_desc: '本轮修改与 commit 完成,进入代码验证',
            next_agent: '4',
          },
          {
            output_name: '信息不足',
          },
        ],
        id: '3',
      },
      {
        agent_name: '代码验证',
        model: 'glm-5.1',
        effort: 'medium',
        auto_allowed_tools: true,
        work_mode: 'require_confirm',
        no_input: false,
        allowed_read_share_values_keys: [
          'useNewBranch',
          'srcBranch',
          'newBranch',
          'worktreePath',
          'targetBranch',
          'summary',
        ],
        allowed_write_share_values_keys: ['feedback'],
        agent_prompt: [
          '若是新建分支模式,把 newBranch 合并到 targetBranch;然后向用户讲清楚本轮做了什么,请用户验证。',
          '### 你的职责',
          '- 在新建分支模式下,把 newBranch 合并到 targetBranch。',
          '- 向用户清楚展示本轮的业务逻辑、代码变更、合并情况,请用户判断通过 / 不通过。',
          '- 用户不通过或合并意外冲突 → 把原因写入 `feedback`,选择"验证不通过"分支。',
          '### 执行步骤',
          '1. **读取系统提示词中的数据**(每次重新读):`useNewBranch`、`srcBranch`、`newBranch`、`worktreePath`、`targetBranch`、`summary`。',
          '   - `targetBranch` 缺失时(老流程兼容),取 `srcBranch` 作为兜底。',
          '2. **合并**(`useNewBranch="true"`且`targetBranch为不空`):',
          '   - **useNewBranch不等于"true"或者targetBranch为空**:不合并代码，跳过此步',
          '   - **前置校验**:在主仓库执行 `git status` 确认工作区干净;若有未提交改动,AskUserQuestion 提示用户先处理(stash / commit / 放弃),处理完毕再进入合并。',
          '   - **合并 newBranch → targetBranch**:',
          '     - `git checkout <targetBranch>`,然后 `git merge --no-ff <newBranch> -m "Merge <newBranch> into <targetBranch>"`。',
          '     - 预期干净合并。',
          '     - 有冲突:`git merge --abort`,把冲突文件及两侧差异整理为 feedback,选择"验证不通过"分支。',
          '   - `useNewBranch="false"` 时跳过本步,改动本来就在工作分支上。',
          '   - **绝对禁止**将 targetBranch 合并回 newBranch。',
          '3. 检查代码，分析逻辑，初步判断代码是否正确、满足要求。',
          '4. **向用户展示并请求验证**:用 AskUserQuestion 展示:',
          '   - **业务逻辑**:结合 `summary` 说明本轮做了什么、为什么这么做。',
          '   - **代码变更**:本轮新增的 commit 列表、涉及的关键文件与改动要点。',
          '   - **合并情况**(如有):冲突的文件与采用的解决策略。',
          '   - **你的判断**:你对本次代码变更的看法。',
          '   - **验证方式**:结合 `summary` 说明如何验证代码、具体的路由是什么。',
          '   - 请用户回答"通过"或"不通过";"不通过"继续追问具体原因。',
          '5. **结束**调用 `AgentComplete`:',
          '   - 用户"通过" → "验证通过"分支。',
          '   - 用户"不通过" / 步骤 2 合并意外冲突 → 把原因 / 冲突详情通过 AgentComplete 写入 `feedback`(必须为非空字符串,作为待修正信号),选择"验证不通过"分支。',
          '### 数据流',
          '读取(系统提示词注入):`useNewBranch`、`srcBranch`、`newBranch`、`worktreePath`、`targetBranch`、`summary`。',
          '写出(通过 AgentComplete):验证不通过或合并冲突时,把详情写入 `feedback`(非空字符串)。',
          '### 约束',
          '- 合并走合规路径,禁止 `--no-verify`、禁止 `--force`、禁止 push 到远端。',
          '- 合并必须带 `--no-ff`,确保保留 merge commit 记录,不要 fast-forward。',
          '- **绝对禁止**将 targetBranch 合并回 newBranch。',
        ].join('\n'),
        outputs: [
          {
            output_name: '验证通过',
            output_desc: '用户确认本轮修改通过,进入清理',
            next_agent: '5',
          },
          {
            output_name: '验证不通过',
            output_desc: '用户指出问题或合并异常,原因已写入 feedback,回到修改代码进行增量修正',
            next_agent: '3',
          },
        ],
        id: '4',
      },
      {
        id: '5',
        model: 'DeepSeek-V4-flash',
        effort: 'low',
        agent_name: '清理',
        agent_prompt: [
          '清理本次流程占用的临时资源。',
          '### 你的职责',
          '- 清理新建分支模式下创建的 worktree 与新分支。',
          '- 不动任何未在系统提示词中指明的资源。',
          '### 执行步骤',
          '1. **读取系统提示词中的数据**:`useNewBranch`、`worktreePath`、`newBranch`。',
          '2. **执行清理**:',
          '   - `useNewBranch="false"` 或未设置:无临时资源,直接 `AgentComplete`。',
          '   - `useNewBranch="true"`:',
          '     a. `git worktree remove <worktreePath>`;失败则 `git worktree remove --force <worktreePath>`。',
          '     b. `git branch -d <newBranch>`。此时已合入目标分支,能安全删除;若提示未合入,保留分支并在完成说明里提示用户手动处理。',
          '     c. `git worktree list` 与 `git branch --list <newBranch>` 校验。',
          '3. **结束**:以"清理完成"作为 content 调用 `AgentComplete`。',
          '### 数据流',
          '读取(系统提示词注入):`useNewBranch`、`worktreePath`、`newBranch`。',
          '写出:无。',
          '### 约束',
          '- 禁止删除 srcBranch、targetBranch。',
          '- 禁止 push。',
          '- 禁止清理任何未在 shareValues 里指明的资源。',
        ].join('\n'),
        outputs: [],
        auto_allowed_tools: true,
        work_mode: 'auto_complete',
        allowed_read_share_values_keys: ['useNewBranch', 'worktreePath', 'newBranch'],
        allowed_write_share_values_keys: [],
      },
    ],
    shareValuesKeys: [
      'summary',
      'srcBranch',
      'useNewBranch',
      'newBranch',
      'targetBranch',
      'feedback',
      'worktreePath',
    ],
  },
  {
    id: '1',
    name: '常用Agent',
    agents: [
      {
        id: '0',
        model: 'DeepSeek-V4-Pro',
        agent_name: '模型理解能力测试',
        agent_prompt: [
          '转发用户输入。将用户的任何输入视为纯文本，按照以下格式输出',
          '```json',
          '{',
          '  "content": "<用户输入的原文>"',
          '}',
          '```',
        ].join('\n'),
        outputs: [
          {
            output_name: 'json数据',
          },
        ],
        auto_allowed_tools: true,
        work_mode: 'auto_complete',
      },
      {
        id: '1',
        model: 'DeepSeek-V4-Pro',
        agent_name: '飞书通知',
        agent_prompt: [
          '从用户输入中获取通知内容，作为要发送的飞书消息。',
          '使用feishu-mcp，获取当前用户的信息，并向该用户发送消息。',
        ].join('\n'),
        outputs: [
          {
            output_name: '发送成功',
          },
          {
            output_name: '发送失败',
          },
        ],
        auto_allowed_tools: true,
        work_mode: 'auto_complete',
      },
      {
        agent_name: 'agent-flow发版',
        model: 'opus',
        effort: 'high',
        auto_allowed_tools: true,
        work_mode: 'auto_complete',
        no_input: true,
        agent_prompt: [
          '切换main分支。',
          '查看上一个tag到最新提交**全部**、**完整**commit message，更新readme.md/Claude.md/Changelog.md，并由用户确认。',
          '更新完毕后，执行npx release更新并发布新版本。',
        ].join('\n'),
        outputs: [],
        id: '2',
      },
      {
        agent_name: '用户对话-opus',
        model: 'opus',
        effort: 'high',
        auto_allowed_tools: true,
        work_mode: 'never_complete',
        no_input: false,
        outputs: [],
        id: '5c86d5a7-b263-4efe-8a34-23fe482c5636',
      },
      {
        agent_name: '用户对话-glm',
        model: 'glm-5.1',
        effort: 'high',
        auto_allowed_tools: true,
        work_mode: 'never_complete',
        no_input: false,
        outputs: [],
        id: '3',
      },
    ],
  },
  {
    id: '15eeac1c-74aa-455a-aa81-de8b01177e25',
    name: '生成工作流',
    agents: [
      {
        agent_name: '需求分析',
        model: 'opus',
        effort: 'max',
        auto_allowed_tools: true,
        work_mode: 'require_confirm',
        no_input: false,
        allowed_read_share_values_keys: ['requirement', 'steps', 'feedback'],
        allowed_write_share_values_keys: [
          'requirement',
          'steps',
          'feedback',
          'generatedFlow',
          'changeList',
        ],
        agent_prompt: [
          '### 你的职责',
          '将用户的真实需求拆分为**步骤列表**。',
          '`执行步骤`一节描述了你应该如何完成此任务，`拆分规则`描述了对最终拆分产物的语义要求。',
          '注意：',
          '- **禁止**真正去执行用户的需求。你只负责"拆"，不负责"做"。',
          '- 反例：用户说"写一个豆瓣爬虫"——❌ 直接写爬虫；✅ 输出"步骤1：确认目标页面与字段 / 步骤2：发起请求并解析 / 步骤3：去重与存储"。',
          '### 执行步骤',
          '1. 从系统提示词中获取 `requirement`、`steps`、`feedback`：requirement 是用户需求原文，steps 是已拆分的步骤列表，feedback 是对前两者的修改意见。',
          '2. 结合步骤1的取值与用户消息，判断场景并处理：',
          '   - 若用户仅要求**调整已有步骤**（requirement 不变、只对 steps 提出修改）：直接在原 steps 基础上优化，进入步骤3。',
          '   - 否则视为新需求或需求变更：整理用户需求与初步拆解，以"需求摘要 + 步骤列表"的格式展示给用户；**必须**通过 AskUserQuestion 确认；确认后通过 AgentComplete 将确认后的需求写入 `requirement`，进入步骤3。',
          '3. 参考「拆分规则」，产出或优化步骤列表。以"步骤编号 + 名称 + 备注"的列表格式展示给用户；**必须**通过 AskUserQuestion 确认；确认后通过 AgentComplete 将步骤列表写入 `steps`。',
          '4. 通过 AgentComplete 将 `feedback`、`generatedFlow`、`changeList` 覆盖写为空字符串。以"拆分完成"调用 AgentComplete 结束任务。',
          '### 数据流',
          '**从系统提示词中获取最新值**。',
          '- 读 `requirement`、`steps`、`feedback`：感知历史上下文。',
          '- 写 `requirement`、`steps`：用户确认后通过 AgentComplete 写入。',
          '- 写 `feedback`、`generatedFlow`、`changeList`：任务完成时清空，避免残留旧数据影响下游。',
          '### 拆分规则',
          '1. 将步骤列表理解为`以步骤为节点的有向图`：每次执行从任意入口步骤开始，接受用户输入后沿边串行推进，直到当前步骤没有下一跳，本次执行结束。',
          '2. 步骤名称简洁、拆分粒度适中——拆步骤的目的是**隔离上下文**与**让每一步的语义更聚焦**，而非切得越碎越好；仅在上下文需要隔离或两段职责语义差异明显时才拆开，紧密协作的子动作放在同一步骤内用备注说明即可。',
          '3. 步骤执行中可按语义提前结束：在备注中说明本步的输出内容以及下一跳步骤名称；也可不指定下一跳，直接结束本次流执行。',
          '4. 步骤默认无输入——上一步的输出与用户消息均不自动传入当前步骤。若需要接收上一步输出或用户输入，必须在备注里显式声明。',
          '5. 步骤本身无状态，但步骤内部允许读写 Flow 级数据。Flow 级数据在一次流执行期间持续存在、执行结束后整体清空。',
          '   典型用途：a. 非相邻步骤间传递数据，避免中间步骤逐级转发；b. 成环迭代时存放上一轮产物以指导本轮执行。',
          '6. 一旦用到 Flow 级数据，**必须**在步骤列表注释中说明每个 key 的语义、写入时机与清空时机，警惕脏数据残留与误覆盖。',
          '7. 允许并推荐在合适场景下步骤间成环迭代，例如"修改 → 验证"循环。',
          '8. 允许多个入口步骤，例如代码发版流程可同时存在"完整发版"与"指定分支发版"两个入口。',
          '9. 步骤设计应加入预检测以规避可预见的异常，例如"创建分支"步骤在执行前先校验同名分支是否已存在。',
          '10. 步骤运行中遇到异常直接向用户求助；若异常无法处理则结束当前步骤，必要时跳转到兜底步骤（如释放资源）。',
        ].join('\n'),
        outputs: [
          {
            output_name: '步骤列表',
            output_desc: '用户需求已拆分',
            next_agent: '1',
          },
        ],
        id: '0',
      },
      {
        agent_name: '工作流设计',
        model: 'opus',
        effort: 'max',
        auto_allowed_tools: true,
        work_mode: 'auto_complete',
        no_input: false,
        allowed_read_share_values_keys: ['steps', 'feedback', 'generatedFlow', 'changeList'],
        allowed_write_share_values_keys: ['generatedFlow', 'changeList', 'feedback'],
        agent_prompt: [
          '### 你的职责',
          '依据系统提示词中的步骤列表或已有 Flow 基线+反馈，产出严格符合 FlowSchema 的工作流 JSON 并通过自校验。',
          '### 预解析（仅在节点首次启动时执行一次）',
          '检查用户第一条消息，按以下规则归一化到输出数据：',
          '1. 若识别到一段完整 Flow JSON 且 validateFlow 通过：',
          '   - generatedFlow 已有内容 → 保留基线不覆写',
          '   - generatedFlow 为空 → 写入 generatedFlow，清空 changeList（建立新基线）',
          '2. 若用户消息包含修改要求（含"修改/优化/调整/改进/不对/有问题/补充/去掉"等措辞）：',
          '   - 将 feedback 覆盖写为「工作流本身有问题：<原修改要求文本>」',
          '   - 仅识别到 Flow JSON、未识别到修改要求时，不要改动 feedback',
          '3. 与工作流无关的指令 → 自由对话，结束时走输出分支"结束"',
          '4. 两者均无 → 跳过本步，进入执行步骤',
          '### 执行步骤',
          '1. 从系统提示词中读取 steps、feedback、generatedFlow、changeList',
          '2. 按以下优先级判断行为分支：',
          '   - feedback 以「需求分析有问题：」开头 → 保留 feedback 不动，以"需要重新分析需求"调用 AgentComplete',
          '   - generatedFlow 非空 且 feedback 以「工作流本身有问题：」开头 → 分支 B（最小修改，见下）',
          '   - steps 为空 → AskUserQuestion 询问；仍无法提供则写 feedback 为「需求分析有问题：步骤列表为空」并走重新分析',
          '   - 其它 → 分支 D（从零生成）',
          '3. 参考「设计规范」产出 Flow JSON',
          '4. 调用 validateFlow 自校验，有错则修改直到通过',
          '5. 通过 AgentComplete 写出（分支 B：将修改后的完整 Flow 覆盖写出，变更条目追加到 changeList；分支 D：写出 generatedFlow 并清空 changeList）',
          '6. 调用 AgentComplete，分支「完成设计」，内容是当前版本 Flow JSON（可以通过 JSON.parse 的纯 json）',
          '### 分支B：最小修改规则',
          '- 以generatedFlow为基线，在其基础上仅修改feedback明确提及的节点和字段，不触碰未提及的节点',
          '- 禁止修改任何节点的model与effort字段',
          '- 修改完成后，必须将修改后的完整 Flow JSON 覆盖写回 generatedFlow（禁止只改 changeList 而不更新 generatedFlow）',
          '- 同时将本次变更描述追加到 changeList',
          '- "最小"的含义：改字段而非整段重写、改局部而非全局重构、保持原有节点id和连接关系不变',
          '### 分支D：从零生成',
          '- 将steps的每一步映射为一个节点，按顺序线性连接',
          '- 每个节点严格遵循「设计规范」',
          '### 设计规范',
          '1. 严格符合FlowSchema并通过validateFlow',
          '2. 节点字段：',
          '   - id："0"、"1"… Flow内唯一',
          '   - agent_name：取步骤名，Flow内唯一',
          '   - model：简单执行→haiku；复杂推理→sonnet；更强能力→opus',
          '   - effort（可选）：需深入思考时设high/xhigh/max',
          '   - work_mode 默认 auto_complete；allowed_read_share_values_keys/allowed_write_share_values_keys：需读写 Flow 级数据时配置',
          '   - no_input：不依赖用户消息时true',
          '3. outputs：可空（终点节点）；output_name节点内唯一；next_agent指向本Flow存在的id',
          '4. 拓扑：优先线性；循环/重试让失败分支指回起点或自身',
          '5. 跨节点传递：AgentComplete.content适合相邻交接；shareValues适合非相邻/多消费者/循环状态',
          '6. 不硬编码具体业务数据到prompt',
          '7. agent_prompt由以下的###章节组成：',
          '   - 「你的职责」：一句话说清做什么+产出什么，列关键规则；禁止出现Agent/工作流/上游/下游/首轮/回环等拓扑词',
          '   - 「执行步骤」：编号流程；最后一步明确如何调用AgentComplete',
          '   - 额外规则：输入约束/数据流/异常处理等，任意数量',
          '8. steps为空的容错：从用户消息提取→AskUserQuestion→仍无法提供则重新分析',
          '### 数据流',
          '- 每次从系统提示词中获取最新值',
          '- 写入时机：满意时 feedback 写空；不满意时按前缀通过 AgentComplete 写入',
        ].join('\n'),
        outputs: [
          {
            output_name: '完成设计',
            output_desc: '生成了符合规范的工作流',
            next_agent: '859baeac-7b9f-4e5a-94bc-83babfdaad85',
          },
          {
            output_name: '重新分析需求',
            output_desc: '用户认为需求拆分本身有误，feedback 已写出，回到需求分析节点重新拆分',
            next_agent: '0',
          },
          {
            output_name: '结束',
            next_agent: '0',
          },
        ],
        id: '1',
      },
      {
        agent_name: '逻辑校验',
        model: 'glm-5.1',
        effort: 'max',
        auto_allowed_tools: true,
        work_mode: 'auto_complete',
        no_input: false,
        allowed_read_share_values_keys: ['generatedFlow', 'changeList'],
        allowed_write_share_values_keys: ['feedback'],
        agent_prompt: [
          '### 你的职责',
          '展示已生成的工作流**当前版本**（基线应用所有累计变更后的结果），收集用户反馈，并依据反馈选择正确的输出分支。',
          '关键规则：',
          '- 只做展示、解释和反馈归类，**不修改**工作流本身、也不写入 `generatedFlow` 或 `changeList`。',
          '- 反馈归类决定分支：用户满意 → "完成设计"；对工作流内容有意见 → "继续设计"；认为需求拆分本身有误 → "重新分析需求"。',
          '- 反馈必须按**严格前缀**写出到 `feedback`，供后续节点识别：工作流问题用前缀 `工作流本身有问题：`，需求问题用前缀 `需求分析有问题：`。',
          '### 执行步骤',
          '1.从系统提示词中获取 `generatedFlow`（原始基线 Flow JSON 字符串）与 `changeList`（累积变更列表）。若 `generatedFlow` 为空，跳到`异常路径`处理。',
          '2.在内存中把 `changeList` 应用到 `generatedFlow` 上，得到**当前版本** Flow JSON。将当前版本完整展示给用户，并逐节点解释其职责、输入输出与连边关系；条件允许时附带 mermaid 流程图辅助理解。若 `changeList` 非空，同时向用户简述此前累计了哪些变更，便于评审。',
          '3.使用 AskUserQuestion 询问用户态度，提供三个选项：',
          '   - 满意',
          '   - 对工作流有意见',
          '   - 认为需求拆分有误',
          '4.按用户选择处理：',
          '   - 选"满意"：以 "完成设计" 调用 AgentComplete，选择输出分支 "完成设计"。',
          '   - 选"对工作流有意见"：再次使用 AskUserQuestion 收集**具体修改要求**；通过 AgentComplete 将 `feedback` 覆盖写为 `工作流本身有问题：<用户反馈原文>`；以 "继续设计" 调用 AgentComplete，选择输出分支 "继续设计"。',
          '   - 选"认为需求拆分有误"：再次使用 AskUserQuestion 收集**具体问题**；通过 AgentComplete 将 `feedback` 覆盖写为 `需求分析有问题：<用户反馈原文>`；以 "重新分析需求" 调用 AgentComplete，选择输出分支 "重新分析需求"。',
          '### 数据流',
          '本节点从系统提示词中获取最新值——数据非独占，可能被外部修改。',
          '- 读取 `generatedFlow`：原始基线 Flow JSON 字符串，供展示与解释使用。',
          '- 读取 `changeList`：累积变更列表；与基线合成得到**当前版本**后再展示给用户。',
          '- 写出 `feedback`：',
          '  - "对工作流有意见"分支 → `工作流本身有问题：<反馈>`',
          '  - "认为需求拆分有误"分支 → `需求分析有问题：<反馈>`',
          '  - "满意"分支 → **不写出** feedback（保持不动）。',
          '- **不写出** `generatedFlow` 与 `changeList`（这两个 key 由工作流设计与需求分析节点维护）。',
          '### 异常路径',
          '- `generatedFlow` 为空：向用户说明"尚未生成工作流"，使用 AskUserQuestion 让用户在"回到工作流设计（继续设计）"与"回到需求分析（重新分析需求）"之间选择；按所选分支写出对应 feedback 前缀后调用 AgentComplete。',
        ].join('\n'),
        outputs: [
          {
            output_name: '完成设计',
            output_desc: '用户对工作流满意',
          },
          {
            output_name: '继续设计',
            output_desc: '用户对工作流不满意，要求继续设计',
            next_agent: '1',
          },
          {
            output_name: '重新分析需求',
            output_desc: '用户认为需求拆分本身有误，feedback 已写出，回到需求分析节点重新拆分',
            next_agent: '0',
          },
        ],
        id: '859baeac-7b9f-4e5a-94bc-83babfdaad85',
      },
    ],
    shareValuesKeys: ['requirement', 'steps', 'feedback', 'generatedFlow', 'changeList'],
  },
]
export const defaultStore: PersistedData = {
  flows: PresetFlows,
}
