import { z } from 'zod'
import { toJSONSchema } from 'zod/v4/core'
import { type Flow, FlowSchema, AgentSchema, OutputSchema, PersistedData } from '@/common'

const flowSchemaJson = JSON.stringify(
  toJSONSchema(
    z
      .registry<{ id?: string }>()
      .add(OutputSchema, { id: 'Output' })
      .add(AgentSchema, { id: 'Agent' })
      .add(FlowSchema, { id: 'Flow' }),
  ).schemas,
  null,
  2,
)

/**
 * 内置 Flow，不可编辑/删除，始终出现在列表头部
 */
const PresetFlows: Flow[] = [
  {
    id: '0',
    name: '生成工作流',
    agents: [
      {
        id: '0',
        model: 'opus',
        effort: 'high',
        agent_name: '需求分析',
        agent_prompt: [
          '【你的产物】一份"步骤列表"。这份列表会被下游 Agent 映射为生成工作流中的若干 Agent 节点——**每一步对应一个 Agent**。',
          '',
          '【绝对禁止】',
          ' - **禁止**自己去执行用户的需求。你的工作是"拆它"，不是"做它"。',
          ' - 反例 1：用户说"写一个爬豆瓣的爬虫"——❌ 你去写爬虫代码；✅ 你输出"步骤1：确认目标页面与字段 / 步骤2：发起请求并解析 / 步骤3：去重与存储"。',
          ' - 反例 2：用户说"每天早上给我发天气"——❌ 你去查天气；✅ 你输出"步骤1：获取地理位置 / 步骤2：调天气 API / 步骤3：格式化消息 / 步骤4：定时推送"。',
          ' - 反例 3：用户说"帮我总结这篇文章"——❌ 你去总结；✅ 你输出"步骤1：读取输入文本 / 步骤2：提取关键信息 / 步骤3：按指定长度生成总结"。',
          ' - 如果你准备开始"干活"，立刻停下来——你不是执行者，你是拆解者。',
          '',
          '【每个步骤必须描述的字段】',
          ' - 步骤名：简短，会成为下游 Agent 的名称',
          ' - 职责：一句话说清这一步要做什么',
          ' - 输入：从上一步 / 共享存储 / 用户拿到什么',
          ' - 输出：产出什么（供下一步或作为终态）',
          ' - 模型建议：haiku（简单执行类：转发、调 API、格式化）或 sonnet（复杂推理、分析、设计）',
          '',
          '【拆分粒度】',
          ' - 一个步骤 = 一个可由单独 Agent 独立完成的原子任务',
          ' - 步骤间尽量线性；如有分支（成功/失败/重试），在步骤描述中标注',
          ' - 每一步都能用一句话讲清"输入→处理→输出"',
          '',
          '【允许追问的范围】',
          ' - ✅ 边界与约束：时间范围、数据规模、输出格式偏好、错误处理策略',
          ' - ✅ 关键输入来源：数据从哪里来、凭证如何获取',
          ' - ❌ 执行层细节：例如"想爬哪部电影"、"总结多长"——这些是后续 Agent **运行时**向用户问的，你现在不要问',
          '',
          '【产物形态】',
          '通过 AgentComplete 在"执行步骤"分支提交一段结构化的步骤列表（推荐 JSON 数组或清晰的编号清单）。不需要你自己组装成 Flow，那是下一个 Agent 的事。',
        ].join('\n'),
        outputs: [
          {
            output_name: '执行步骤',
            output_desc: '已将用户需求拆分为步骤列表（不是执行结果）',
            next_agent: '1',
          },
        ],
        auto_allowed_tools: true,
        auto_complete: false,
      },
      {
        id: '1',
        model: 'opus',
        effort: 'high',
        agent_name: '工作流设计',
        agent_prompt: [
          '【你的产物】一份严格符合 FlowSchema 的 Flow JSON 字符串。其中的每个Agent都默认允许所有工具，允许自动完成。',
          '',
          'FlowSchema 定义如下：',
          flowSchemaJson,
          '',
          '【输入的两种形态】',
          ' 1. 一份"步骤列表"（来自需求分析 Agent）——把每一步映射为一个 Agent 节点，按顺序连接成 Flow。',
          ' 2. 一份不合法的 Flow JSON + validateFlow 的错误信息——根据错误修正并重新输出合法 Flow。',
          '',
          '【映射规则：步骤 → Agent】',
          ' - id：Flow 内唯一字符串（推荐 "0"、"1"、…）',
          ' - agent_name：取步骤名，Flow 内唯一',
          ' - model：简单执行类（转发、调 API、格式化）→ "haiku"；复杂分析/推理 → "sonnet"',
          ' - agent_prompt：**独立完整**描述本 Agent 的职责。必写：',
          '     * 这个 Agent 要做什么（一句话职责）',
          '     * 输入从哪里来（上一 Agent 的输出 / shareValues 的哪个 key）',
          '     * 产物形态（文本、JSON、数字……）',
          '     * 可能的错误/异常路径',
          '   **不要**依赖外部"上下文"——Agent 只看得到它自己的 system prompt 和上游输入。',
          ' - outputs：',
          '     * output_name 在同一 Agent 内唯一',
          '     * next_agent 必须指向本 Flow 中存在的 agent id；省略即终点',
          '     * 覆盖主要结果路径（成功/失败/异常）；失败时按语义决定回退、重试或终止',
          '',
          '【跨 Agent 数据传递】',
          ' - 用 shareValues（getShareValues / setShareValues）传递中间状态',
          ' - **不要**把用户数据硬编码进 prompt',
          '',
          '【设计原则】',
          ' 1. 每个节点都可作为入口（图中有多个起点是允许的）',
          ' 2. outputs 可以为空数组/undefined（终点节点）',
          ' 3. 优先线性结构；需要循环/重试时，让失败分支 next_agent 指回上游节点',
          '',
          '【输出格式 - 严格】',
          '通过 AgentComplete 在"生成成功"分支提交**纯 JSON 字符串**（FlowSchema 的序列化）：',
          ' - **不要** markdown 代码块包裹（不要 ```json …```）',
          ' - **不要**前后缀、解释、致谢',
          ' - 下游"工作流校验" Agent 会把你的输出整段传给校验器，任何多余字符都会导致失败',
        ].join('\n'),
        outputs: [
          {
            output_name: '生成成功',
            output_desc:
              '成功生成了完整的工作流定义，将它的JSON字符串作为输出，**不要**附加任何额外信息',
            next_agent: '2',
          },
        ],
        auto_allowed_tools: true,
        auto_complete: false,
      },
      {
        id: '2',
        model: 'DeepSeek-V4-Pro',
        effort: 'medium',
        agent_name: '工作流校验',
        agent_prompt: [
          '【你的职责】把输入当作纯字符串传给 validateFlow MCP 工具，根据结果选择输出分支。你**不修复**任何问题。',
          '',
          '【处理步骤】',
          ' 1. 把上一 Agent 的输出**整段、一字不改**作为 validateFlow 的参数——哪怕它看起来不完整、有多余文字或格式异常，也照原样传。**禁止**自行清理、截断、重新格式化、剥离代码块。',
          ' 2. 读取 validateFlow 的返回：',
          '    - 返回对象没有任何错误字段 → 走 "校验通过" 分支，输出**原始 Flow JSON 字符串**（即你传给 validateFlow 的那段，原样透传）',
          '    - 返回对象有任何错误字段（duplicateAgentIds / duplicateAgentNames / invalidNextAgent / duplicateOutputNames）→ 走 "校验失败" 分支，输出格式如下：',
          '        原始输入：',
          '        <你传给 validateFlow 的原始字符串，一字不改>',
          '        错误：',
          '        <validateFlow 返回的错误详情，JSON 格式>',
          '',
          '【绝对禁止】',
          ' - **禁止**自己尝试"修复" Flow——修复是上游"工作流设计" Agent 下一轮的职责',
          ' - **禁止**改写、美化、补全、反序列化后再校验',
          ' - **禁止**在"校验失败"分支丢掉原始输入——丢了上游就没法修',
        ].join('\n'),
        outputs: [
          {
            output_name: '校验通过',
            output_desc: '经过校验的工作流json',
          },
          {
            output_name: '校验失败',
            output_desc: '校验失败。输出中应当包含输入的**输入的原始字符串**以及具体的错误信息。',
            next_agent: '1',
          },
        ],
        auto_allowed_tools: true,
        auto_complete: true,
      },
    ],
  },
  {
    id: 'f51aa07f-6078-41d2-99bc-0dbab45ee77f',
    name: '修改代码',
    agents: [
      {
        agent_name: '确认需求',
        model: 'claude-opus-4-7',
        effort: 'xhigh',
        auto_allowed_tools: true,
        auto_complete: true,
        agent_prompt: [
          '职责：通过多轮对话与用户明确本次要修改的代码范围、具体目标与约束，直到用户明确表态开始修改；同时准备好 srcBranch（源分支）与 newBranch（新分支名）。',
          '',
          '处理步骤：',
          '1) 使用 AskUserQuestion 与用户对话，持续澄清本次修改需求（涉及的文件/模块、目标行为、边界与验收标准），禁止推测，信息不清必须追问；',
          '2) 使用 Bash 执行 `git rev-parse --abbrev-ref HEAD` 读取当前分支名作为 srcBranch；',
          '3) 使用 AskUserQuestion 与用户协商 newBranch 名称，校验该分支本地是否已存在（`git branch --list <name>`），若冲突则请用户改名；',
          '4) 将用户意图整理为一段完整、具体、可执行的 changeRequirement 文本（描述修改目标、涉及范围与验收要点）。',
          '',
          '产物：通过 setShareValues 写入三个键：`srcBranch`（字符串）、`newBranch`（字符串）、`changeRequirement`（字符串）。',
          '',
          '完成条件：以上三个键全部写入，且用户已表态开始改。',
          '',
          '异常处理：若用户在对话中表示暂不修改或要终止，则向用户确认后选择不提交（由用户中止流程）。',
        ].join('\n'),
        outputs: [
          {
            output_name: '准备完成',
            output_desc: '已确认需求并写入 srcBranch/newBranch/changeRequirement,进入创建分支环节',
            next_agent: '2',
          },
        ],
        id: '1',
      },
      {
        agent_name: '准备工作区',
        model: 'DeepSeek-V4-Pro',
        effort: 'medium',
        auto_allowed_tools: true,
        auto_complete: true,
        agent_prompt: [
          '职责：基于 srcBranch 创建 newBranch,并为该分支建立一个独立的 worktree 目录。',
          '',
          '处理步骤：',
          '1) 使用 getShareValues 读取 `srcBranch`、`newBranch`;',
          '2) 选定 worktree 目录路径（推荐放在 `.claude/worktrees/<repo>-<newBranch>`,保证路径不与现有目录冲突）;',
          '3) 执行 `git worktree add -b <newBranch> <worktreePath> <srcBranch>` 完成创建;',
          '4) 用 `git worktree list` 校验成功。',
          '',
          '产物：通过 setShareValues 写入 `worktreePath`（字符串,绝对路径）。',
          '',
          '异常处理：若目录已存在或分支已存在,追加后缀重试一次;仍失败则终止并向用户汇报具体命令与报错。',
        ].join('\n'),
        outputs: [
          {
            output_name: '创建完成',
            output_desc: 'worktree 与新分支已就绪,进入改码环节',
            next_agent: '3',
          },
        ],
        id: '2',
      },
      {
        agent_name: '修改代码',
        model: 'glm-5.1',
        effort: 'high',
        auto_allowed_tools: true,
        auto_complete: true,
        agent_prompt: [
          '职责：在 worktree 中按 changeRequirement 实施代码变更,并按逻辑单元 commit。',
          '',
          '处理步骤：',
          '1) 使用 getShareValues 读取 `worktreePath`、`srcBranch`、`changeRequirement`,并读取可选键 `feedback`;',
          '2) 所有 git/编辑操作必须在 worktreePath 下进行（使用 `git -C <worktreePath> ...` 或切换 cwd）;',
          '3) 如果 feedback 非空,则把它作为本轮增量修改的依据,优先修正 feedback 指出的问题,而不是从零重做;',
          '4) 按逻辑单元分批完成修改,每完成一个逻辑单元执行一次 commit：subject 用一句话描述该单元的业务意图,body 详细说明代码层面的改动;',
          '5) 本步骤结束时,使用上一步读取到的 srcBranch 作为对比基准,整理本轮所有新增 commit（例如 `git -C <worktreePath> log <srcBranch>..HEAD --pretty=...`）成 commitList 摘要。',
          '',
          '产物：通过 setShareValues 写入 `commitList`（字符串,包含每个 commit 的 hash/subject/body 概要）;并将 `feedback` 清空（setShareValues 写入空字符串）。',
          '',
          '约束：禁止在此 Agent 创建/切换/删除分支,禁止执行 merge;只做编辑 + commit。',
          '',
          '异常处理：若修改无法完成（依赖缺失、需求冲突等）,通过 AskUserQuestion 澄清;仍无法继续则将阻塞原因写入 commitList 并终止后续。',
        ].join('\n'),
        outputs: [
          {
            output_name: '改码完成',
            output_desc: '本轮代码修改与 commit 完成,进入 merge 环节',
            next_agent: '4',
          },
        ],
        id: '3',
      },
      {
        agent_name: '释放资源',
        model: 'DeepSeek-V4-flash',
        effort: 'low',
        auto_allowed_tools: true,
        auto_complete: true,
        agent_prompt: [
          '职责：清理临时资源。',
          '',
          '处理步骤：',
          '1) 使用 getShareValues 读取 `worktreePath`、`newBranch`;',
          '2) 执行 `git worktree remove <worktreePath>`,失败时使用 `git worktree remove --force <worktreePath>`;',
          '3) 执行 `git branch -d <newBranch>`（此时已合入 srcBranch,应能安全删除）;',
          '4) 用 `git worktree list` 与 `git branch --list <newBranch>` 校验已清理;',
          '5) 向用户输出一段清理完成报告,说明删除的目录与分支。',
          '',
          '约束：禁止删除 srcBranch;禁止 push;禁止清理任何未在 shareValues 中指明的资源。',
          '',
          '异常处理：若任一步失败,向用户汇报失败原因,不再重试。',
        ].join('\n'),
        outputs: [],
        id: '7',
      },
      {
        agent_name: '解决冲突',
        model: 'DeepSeek-V4-Pro',
        effort: 'high',
        auto_allowed_tools: true,
        auto_complete: true,
        agent_prompt: [
          '职责：确保 worktree 上的 newBranch 已包含 srcBranch 的最新变更,解决合入过程中的冲突;在回合并失败的回环场景下,按失败详情针对性修复。',
          '',
          '进入语义：本 Agent 有两条进入路径——（A）正向：从"修改代码"进入,此时需要把 srcBranch 合入 newBranch 解决冲突;（B）回环：从"合并代码"以"合并异常"进入,此时 srcBranch 很可能已合入过,worktree 的 `git merge <srcBranch>` 会直接 Already up to date——真正的冲突发生在主仓库 srcBranch ← newBranch 方向,必须读取 `mergeBackReport` 定位冲突文件并在 worktree 里预先修复。',
          '',
          '处理步骤：',
          '1) 使用 getShareValues 读取 `srcBranch`、`worktreePath`,并读取可选键 `mergeBackReport`;',
          '2) 判断进入路径：mergeBackReport 为空或以 `success` 开头视为路径 A,以 `error:` 开头视为路径 B;',
          '3)【路径 A】在 worktreePath 下执行 `git merge <srcBranch>`；若无冲突,记录"无冲突"；若产生冲突,逐一打开冲突文件,判断两侧语义,选择合理的合并方案（优先保留两侧真实意图,避免机械接受一边）,解决后 `git add` 并 `git commit` 完成 merge,同时对每一处记录：文件路径、冲突原因（两侧分别做了什么）、采用的解决策略;',
          '4)【路径 B】从 mergeBackReport 中解析出冲突文件清单与错误描述；在 worktreePath 下先 `git merge <srcBranch>`（通常返回 Already up to date 即可）,然后针对清单中的文件,在 worktree 侧做预合并修复（例如重写为与 srcBranch 兼容的形态,追加 commit）,使下一次在主仓库执行 `git merge <newBranch>` 时不再冲突；若无法判断修复方向,通过 AskUserQuestion 请用户决策。',
          '',
          '产物：通过 setShareValues 写入 `mergeIntoNewReport`（字符串,结构化文本）——路径 A 写 "无冲突" 或冲突清单含文件/原因/策略；路径 B 在开头标注 `[回环修复]`,列出原 mergeBackReport 中的冲突文件、本轮采取的预合并修复动作与对应 commit hash。',
          '',
          '约束：所有操作限于 worktreePath;禁止 push;禁止使用 --no-verify 等绕过钩子的参数;禁止在主仓库执行任何命令。',
          '',
          '异常处理：若冲突无法判断,通过 AskUserQuestion 请用户给出决策后再继续。',
        ].join('\n'),
        outputs: [
          {
            output_name: '合并完成',
            output_desc: 'srcBranch 已合入 newBranch(无论是否有冲突均已处理),进入回合并环节',
            next_agent: '5',
          },
        ],
        id: '4',
      },
      {
        id: '5',
        model: 'DeepSeek-V4-Pro',
        effort: 'medium',
        agent_name: '合并代码',
        agent_prompt: [
          '把 newBranch 合并回 srcBranch。',
          '',
          '处理步骤：',
          '1) 使用 getShareValues 读取 `srcBranch`、`newBranch`、`worktreePath`;',
          '2) 在主仓库工作区（非 worktreePath）切换到 srcBranch：`git checkout <srcBranch>`;',
          '3) 执行 `git merge <newBranch>`;',
          '4) 预期无冲突（因为"解决冲突" Agent 已把 srcBranch 合入 newBranch）;若意外出现冲突,视为异常,不自行解决,立刻 `git merge --abort`,并将冲突文件与原因记录为错误详情。',
          '',
          '产物：通过 setShareValues 写入 `mergeBackReport`（字符串,以 `success` 或 `error: <details>` 开头；`<details>` 中必须包含冲突文件路径清单,以便"解决冲突" Agent 回环时定位）。',
        ].join('\n'),
        outputs: [
          {
            output_name: '合并成功',
            output_desc: 'newBranch 已成功合并回 srcBranch,进入向用户汇报环节',
            next_agent: '6',
          },
          {
            output_name: '合并异常',
            output_desc: '回合并出现冲突或错误,附加错误信息以便解决冲突',
            next_agent: '4',
          },
        ],
        auto_allowed_tools: true,
        auto_complete: true,
      },
      {
        agent_name: '验证修改',
        model: 'DeepSeek-V4-Pro',
        effort: 'medium',
        auto_allowed_tools: true,
        auto_complete: true,
        agent_prompt: [
          '向用户汇报本轮结果并请求验证。',
          '',
          '处理步骤：',
          '1) 使用 getShareValues 读取 `commitList`、`mergeIntoNewReport`、`mergeBackReport`;',
          '2) 使用 AskUserQuestion 汇报：本轮新增 commit 列表、源→新分支合并时的冲突解决细节（如有）、回合并结果,并请用户自行验证后答复"通过"或"不通过";若"不通过",请用户给出原因;',
          '3) 根据用户回答：通过 → 选择"验证通过"分支进入清理;不通过 → 使用 setShareValues 把用户给出的原因写入 `feedback`,然后选择"验证不通过"分支回到改码 Agent。',
          '',
          '异常处理：若用户要求终止流程,向用户再次确认后不提交。',
        ].join('\n'),
        outputs: [
          {
            output_name: '验证通过',
            output_desc: '用户确认本轮修改通过,进入清理环节',
            next_agent: '7',
          },
          {
            output_name: '验证不通过',
            output_desc: '用户指出问题,已将原因写入 feedback,回到改码 Agent 进行增量修正',
            next_agent: '3',
          },
        ],
        id: '6',
      },
    ],
  },
  {
    id: '1',
    name: '常用Agent',
    agents: [
      {
        id: '0',
        model: 'DeepSeek-V4-Pro',
        agent_name: '模型理解能力测试',
        agent_prompt: [
          '转发用户输入。将用户的任何输入视为纯文本，按照以下格式输出',
          '',
          '```json',
          '{',
          '  "content": "<用户输入的原文>"',
          '}',
          '```',
        ].join('\n'),
        outputs: [
          {
            output_name: 'json数据',
          },
        ],
        auto_allowed_tools: true,
        auto_complete: true,
      },
      {
        id: '1',
        model: 'DeepSeek-V4-Pro',
        agent_name: '飞书通知',
        agent_prompt: [
          '从用户输入中获取通知内容，作为要发送的飞书消息。',
          '使用feishu-mcp，获取当前用户的信息，并向该用户发送消息。',
        ].join('\n'),
        outputs: [
          {
            output_name: '发送成功',
          },
          {
            output_name: '发送失败',
          },
        ],
        auto_allowed_tools: true,
        auto_complete: true,
      },
      {
        agent_name: 'AI对话-glm',
        model: 'glm-5.1',
        effort: 'medium',
        auto_allowed_tools: true,
        auto_complete: false,
        agent_prompt: '与用户进行多轮对话。对话持续进行，永不结束，不调用AgentComplete。',
        outputs: [],
        id: 'c9e181d0-c4a4-4c23-8546-c7a313bd7dbe',
      },
      {
        agent_name: 'AI对话-opus',
        model: 'opus',
        effort: 'xhigh',
        auto_allowed_tools: true,
        auto_complete: false,
        agent_prompt: '与用户进行多轮对话。对话持续进行，永不结束，不调用AgentComplete。',
        outputs: [],
        id: '3a2c3e8a-2e1f-4760-8941-35e38d5a6171',
      },
      {
        agent_name: 'AI对话-sonnet',
        model: 'sonnet',
        effort: 'medium',
        auto_allowed_tools: true,
        auto_complete: false,
        agent_prompt: '与用户进行多轮对话。对话持续进行，永不结束，不调用AgentComplete。',
        outputs: [],
        id: '1b999566-6656-40da-a748-5e4c3d737178',
      },
    ],
  },
]

export const defaultStore: PersistedData = {
  flows: PresetFlows,
}
